name = "northstowekarate"
compatibility_date = "2025-09-07"
workers_dev = true
preview_urls = true

[assets]
directory = "_site"

[[routes]]
pattern = "www.northstowekarate.com"
custom_domain = true

